<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Sales.aspx.cs" Inherits="CoffeeShop.Item.Sales" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="form-horizontal">
        <hr />
        <asp:HiddenField ID="IdHiddenField" runat="server" />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-2">
                <asp:Label runat="server" ID="lblSerial" AssociatedControlID="txtSerial" CssClass="control-label">Serial</asp:Label>
                <asp:TextBox runat="server" ID="txtSerial" CssClass="form-control" TextMode="Number" ReadOnly="true" />
            </div>
            <div class="col-md-2">
                <asp:Label runat="server" ID="lblDate" AssociatedControlID="txtDate" CssClass="control-label">Date</asp:Label>
                <asp:TextBox runat="server" ID="txtDate" CssClass="form-control" ReadOnly="true" />
            </div>
            <div class="col-md-2">
                <asp:Label runat="server" ID="lblCashierName" AssociatedControlID="txtCashierName" CssClass="control-label">Cashier Name</asp:Label>
                <asp:TextBox runat="server" ID="txtCashierName" CssClass="form-control" ReadOnly="true" />
            </div>
            <div class="col-md-2">
                <asp:Label runat="server" ID="lblCustomerName" AssociatedControlID="txtCustomerName" CssClass="control-label">Customer Name</asp:Label>
                <asp:TextBox runat="server" ID="txtCustomerName" CssClass="form-control" />
                <asp:RequiredFieldValidator runat="server" ControlToValidate="txtCustomerName"
                    CssClass="text-danger" ErrorMessage="The Customer Name field is required." />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-2">
                <asp:Label runat="server" ID="lblCategories" AssociatedControlID="CategoriesDropDownList" CssClass="control-label">Select Category</asp:Label>
                <asp:DropDownList ID="CategoriesDropDownList" runat="server" CssClass="form-control" AutoPostBack="true" OnSelectedIndexChanged="CategoriesDropDownList_SelectedIndexChanged"></asp:DropDownList>
            </div>
            <div class="col-md-2">
                <asp:Label runat="server" ID="lblItems" AssociatedControlID="ItemsDropDownList" CssClass="control-label">Select Item</asp:Label>
                <asp:DropDownList ID="ItemsDropDownList" runat="server" CssClass="form-control" AutoPostBack="true" OnSelectedIndexChanged="ItemsDropDownList_SelectedIndexChanged"></asp:DropDownList>
            </div>
            <div class="col-md-2">
                <asp:Label runat="server" ID="lblItemPrice" AssociatedControlID="txtItemPrice" CssClass="control-label">Item Price</asp:Label>
                <asp:TextBox runat="server" ID="txtItemPrice" CssClass="form-control" ReadOnly="true" />
            </div>
            <div class="col-md-2">
                <asp:Label runat="server" ID="lblQty" AssociatedControlID="txtQty" CssClass="control-label">Quantity</asp:Label>
                <asp:TextBox runat="server" ID="txtQty" CssClass="form-control" TextMode="Number" AutoPostBack="true" OnTextChanged="txtQty_TextChanged" />
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-offset-4 col-md-3">
                <br />
                <asp:Button runat="server" ID="AddButton" Text="Add" CssClass="btn btn-info" OnClick="AddButton_Click" />
                <asp:Button runat="server" ID="DeleteButton" Text="Check Print" CssClass="btn btn-info" OnClick="DeleteButton_Click" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <asp:GridView ID="ItemSalesGridView" runat="server" EmptyDataText="No Order Available Here" Width="100%" CssClass="table table-striped table-bordered table-hover" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="10" ForeColor="Black" GridLines="Horizontal" AllowPaging="false" CellSpacing="10" OnRowDeleting="ItemSalesGridView_RowDeleting" OnRowCancelingEdit="ItemSalesGridView_RowCancelingEdit" OnRowEditing="ItemSalesGridView_RowEditing" OnRowUpdating="ItemSalesGridView_RowUpdating" OnRowDataBound="ItemSalesGridView_RowDataBound">
                    <Columns>
                        <asp:TemplateField HeaderText="Name">
                            <ItemTemplate>
                                <asp:Label ID="lblName" runat="server" Text='<%#Eval("Name") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEName" runat="server" Text='<%#Eval("Name") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Qty">
                            <ItemTemplate>
                                <asp:Label ID="lblQty" runat="server" Text='<%#Eval("Qty") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEQty" runat="server" Text='<%#Eval("Qty") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Unit">
                            <ItemTemplate>
                                <asp:Label ID="lblUnit" runat="server" Text='<%#Eval("Perprice") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEUnit" runat="server" Text='<%#Eval("Perprice") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Total">
                            <ItemTemplate>
                                <asp:Label ID="lblTotal" runat="server" Text='<%#Eval("Subprice") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtETotal" runat="server" Text='<%#Eval("Subprice") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <PagerStyle Font-Bold="true" Font-Size="Small" ForeColor="#3399FF" />
                </asp:GridView>
            </div>

            <div class="col-md-2">
                <asp:Label runat="server" ID="lblSubTotal" AssociatedControlID="txtSubTotal" CssClass="control-label">Grand Total</asp:Label>
                <asp:TextBox runat="server" ID="txtSubTotal" CssClass="form-control" ReadOnly="true" AutoPostBack="true" />

                <asp:Label runat="server" ID="lblTotalCost" AssociatedControlID="txtTotalCost" CssClass="control-label">Payable Amount</asp:Label>
                <asp:TextBox runat="server" ID="txtTotalCost" CssClass="form-control" ReadOnly="true" />
            </div>

            <div class="col-md-2">
                <asp:Label runat="server" ID="lblDiscount" AssociatedControlID="txtDiscount" CssClass="control-label">Discount</asp:Label>
                <asp:TextBox runat="server" ID="txtDiscount" CssClass="form-control" AutoPostBack="true" OnTextChanged="txtDiscount_TextChanged" />

                <asp:Label runat="server" ID="lblPaidAmount" AssociatedControlID="txtPaidAmount" CssClass="control-label">Paid Amount</asp:Label>
                <asp:TextBox runat="server" ID="txtPaidAmount" CssClass="form-control" OnTextChanged="txtPaidAmount_TextChanged" AutoPostBack="true" />
            </div>

            <div class="col-md-offset-2 col-md-2">
                <asp:Label runat="server" ID="lbl" AssociatedControlID="txtItemPrice" CssClass="control-label">Changes : </asp:Label>
                <asp:Label runat="server" ID="lblChanges" AssociatedControlID="txtItemPrice" CssClass="control-label" ForeColor="#66ccff">0.00</asp:Label>
            </div>
            <div class="col-md-offset-2 col-md-3">
                <br />
                <asp:Button runat="server" ID="PrintButton" Text="Print" CssClass="btn btn-info" OnClick="PrintButton_Click" />
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" rel="stylesheet" />
    <script>
        $('#<%=CategoriesDropDownList.ClientID%>').chosen();
        $('#<%=ItemsDropDownList.ClientID%>').chosen();
    </script>
</asp:Content>
